from __future__ import annotations

import json
import os

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from serving.app.issue_handler import handle_issue
from serving.app.schemas import EvalSummaryResponse, IssueRequest, IssueRunResponse

app = FastAPI(
    title="Multi-Agent SWE-bench Resolution System",
    description="Autonomous multi-agent system that resolves GitHub issues via "
                 "generated, tested, and validated code patches.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.environ.get("CORS_ORIGINS", "http://localhost:5173").split(","),
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/api/issues/resolve", response_model=IssueRunResponse)
def resolve_issue(request: IssueRequest):
    try:
        return handle_issue(request)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Pipeline error: {e}")


@app.get("/api/eval/summary", response_model=EvalSummaryResponse)
def eval_summary():
    """Serves the real eval_report.md-derived summary once it has actually
    been generated by evaluation/run_swebench_eval.py. Returns 404 (not a
    fabricated summary) if no evaluation has been run yet."""
    report_json_path = "evaluation/eval_summary.json"
    if not os.path.isfile(report_json_path):
        raise HTTPException(
            status_code=404,
            detail="No evaluation has been run yet. See evaluation/eval_report.md "
                   "for instructions to generate real results.",
        )
    with open(report_json_path) as f:
        data = json.load(f)
    return EvalSummaryResponse(**data)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("serving.app.main:app", host="0.0.0.0", port=8000, reload=True)
